GafferHQ/gafferhq.github.io

_includes/header.html
Point to specific version of documentation. This has two benefits :
- People can bookmark links that aren't going to be broken when documentation gets restructured.
- We won't have to manage these awkward ["copy latest docs to root" commits](https://github.com/GafferHQ/documentation/commit/afc2dff47939b60bb11687422c2ce8f03413b6f0) any more, which will make it slightly easier to automate the documentation upload as part of the Gaffer release process.
Any concerns with this @medubelko?
=> Documentation link

Gemfile
This was breaking the Docker-based server setup documented in README.md. I don't know what it was there for, but assume it was because it was in the original instructions at https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/. The latest version of that page no longer includes that gem, and I've verified that the website still generates locally both with and without Docker.
=> Gemfile : Remove `therubyracer`

_config.yml
Didn't notice the GitHub-pages version of Jekyll had future posts enabled by default. Should be fixed with this.
=> Config : Prevent future posts from publishing immediately

_config.yml, _includes/footer.html, _posts/2015-07-8-jurassicWorldInterview.md, _posts/2015-10-21-appleseedInterview.md, community.html, index.html, news.html
@johnhaddon I grabbed your PR on a local VM, and fixed all the errors the proofer threw at me. This PR fixes the legitimate HTML issues with the site, and some of the illegitimate ones.
Most of the errors should be gone, but I couldn't reproduce the numerous `internally linking to <URI>, which doesn't exist` errors that Travis reported, caused by nav links like `{{ site.baseurl }}/downloads/` in `header.html`. They are in fact perfectly valid HTML. I suspect there's a conflict between Jekyll's directory structure/variable and Nokogiri. A few other public projects have mentioned running into this issue, but I didn't find any solutions. I believe some projects just live with the errors.
I suppose the best course of action now is to merge this and see what errors remain with your Travis PR. …
=> Fix HTML errors

.gitignore, .travis.yml, Gemfile
This is a copy of John's Travis config (#22) so we can re-test the validator with the fixes from https://github.com/gafferhq/gafferhq.github.io/pull/23.
=> Configure Travis CI for site validation

_config.yml, _posts/2016-08-03-siggraphAndDigiPro.md, _posts/2019-02-14-announce-gaffer-53.md
There were a number of broken links that were causing CI tests to fail (and have been for a while). We need to treat CI failures are blocking.
=> Link fixes

.travis.yml, Gemfile
GitHubPages only supports a white-listed subset of Gems. This causes builds
in environments that mirror what is available on GitHubPages to fail.
html-proofer is used on travis for validation of links, so this moves it t
a travis-only place.
=> Fix Docker builds

_includes/footer.html
The site's JS (in particular, the carousel and nav) are broken. I'm not sure when exactly this happened. Both FF and Chrome are blocking the URL to jQuery's site, because it's an old unsecured HTTP link. This will hopefully fix that.
The new link is also to jQuery 2, which should speed up load times a little.
=> Update jQuery version

.github/workflows/update.yml, .travis.yml, README.md, _config.yml, download.html, update.py
This created https://github.com/GafferHQ/gafferhq.github.io/pull/60 automatically. We need to merge this and that at the same time, as the new downloads page only works with the update Gaffer version.
=> Add auto-update using GitHub Actions

.github/workflows/check.yml, .github/workflows/update.yml
As described at actions/virtual-environments#3287 support for Ubuntu 16.04 was dropped by GitHub on September 20th. Our CI workflows are now failing to start because they can't find a worker.
Our choices are 18.04 or 20.04. In the absence of any other reason, I've chosen 20.04 because it will last longer before we have to update again.
=> GitHub Workflows : Update host OS to Ubuntu 20.04

blog.html
Not to the ancient news section.
=> Redirect `www.gafferhq.org/blog` to `blog.gafferhq.org`

_includes/footer.html, index.html
This updates the embedded video on the homepage to a more up to date recording as well as changing the Vimeo link in the footer to point to the recently renamed `gafferhq` Vimeo account.
=> Update homepage video and Vimeo account 

_includes/footer.html
This updates the footer to include a link to the Twitter account.
=> Add link to GafferHQ Twitter account

.github/workflows/check.yml
This is an attempt at fixing the current CI failures when installing `html-proofer`. According to [this](https://rubygems.org/gems/html-proofer/versions/5.0.0) `html-proofer` 5.0.0 dropped support for Ruby 2.6 so won't work in the current CI environment, so this change should limit the gem install to previous compatible versions.
=> CI : Limit html-proofer install to versions < 5.0.0

.github/workflows/check.yml
The nokogiri version installed by html-proofer no longer supports Ruby 2.6.  `actions/setup-ruby@v1` supports Ruby 2.7, so updating would be preferable to attempting to lock to an old nokogiri version.
Putting this up to see what happens on CI... :crossed_fingers:
=> CI : Update to Ruby 2.7

_config.yml, download.html
Update to Gaffer 1.2.0.1 and add the Windows release to the download page.
- Replace Linux Python 2 & 3 download links with Linux and Windows links.
- Add Windows 10/11 to required operating systems.
- Update Arnold and 3Delight versions described in the 3rd-party tools section.
=> Update Gaffer to 1.2.0.1 and add Windows download

.github/workflows/update.yml, update.py
Same fix as https://github.com/GafferHQ/documentation/pull/92 after `distutils` removal from Python 3.12.
=> Update workflow : Avoid `distutils`

.github/workflows/check.yml, _config.yml, download.html, index.html, resources.html
Updated download page to include links for the 1.4 GCC 9 and GCC 11 release packages, and a touch of overall spring cleaning in honour of the Gaffer 1.4.0.0 release...
=> Gaffer 1.4 updates

download.html
Quick attempt at sticking a link to the release notes below the download links.
=> Add link to release notes

.github/workflows/check.yml, .github/workflows/update.yml
GitHub Pages has been [updated](https://pages.github.com/versions/) to run Ruby 3.3, so we update to match. This allows us to unpin the `nokogiri` and `html-proofer` gem versions to fix the currently broken on Ruby 2.7 `html-proofer` checks. 
At the same time, we update the `checkout` and `cache` actions versions to modern Node20 supported actions.
=> CI : Update to Ruby 3.3

.github/workflows/check.yml, .github/workflows/update.yml
Support for Ubuntu 20.04 is being removed by GitHub and 24.04 is now the latest available.
=> CI : Run on Ubuntu 24.04
